[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "paq_Datos_SLC"
version = "0.1.0"
description = "Paquete para obtener y limpiar observaciones del MPC y conseguir los datos necesarios para la curva de luz secular de cuerpos menores."
authors = [
    { name="Emiliano Gómez", email="emigomeza04@gmail.com" }
]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.9"
dependencies = [
    "pandas",
    "polars",
    "numpy",
    "astroquery",
    "requests"
]

[tool.setuptools]
packages = ["paq_Datos_SLC"]   # 👈 debe coincidir con el nombre de tu carpeta de código
include-package-data = true

[tool.setuptools.package-data]
paq_Datos_SLC = ["family.json"]
